"use client";

import { useState } from "react";
import type { FuelPlanOutput, ScheduleItem } from "@/lib/fuelEngine";

interface PlanResultsProps {
  result: FuelPlanOutput;
  planValues: {
    plan_type: string;
    sport: string;
    effort: string;
    duration: string;
  } | null;
  onStartOver: () => void;
}

function MetricCard({
  label,
  value,
  sub,
}: {
  label: string;
  value: string;
  sub?: string;
}) {
  return (
    <div
      style={{
        background: "var(--surface-2)",
        border: "1px solid var(--border)",
        borderRadius: "4px",
        padding: "16px",
      }}
    >
      <p
        style={{
          fontSize: "11px",
          color: "var(--text-muted)",
          marginBottom: "6px",
          textTransform: "uppercase",
          letterSpacing: "0.08em",
        }}
      >
        {label}
      </p>
      <p style={{ fontSize: "22px", fontWeight: 700, color: "var(--text)", lineHeight: 1.1 }}>
        {value}
      </p>
      {sub && (
        <p style={{ fontSize: "11px", color: "var(--text-muted)", marginTop: "4px" }}>
          {sub}
        </p>
      )}
    </div>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <p
      style={{
        fontSize: "11px",
        color: "var(--text-muted)",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        marginBottom: "12px",
        paddingBottom: "8px",
        borderBottom: "1px solid var(--border)",
      }}
    >
      {children}
    </p>
  );
}

function buildCopyText(result: FuelPlanOutput): string {
  const lines: string[] = [];
  lines.push("concept//fuel - Fuel Plan");
  lines.push("=".repeat(40));
  lines.push(`Carb target:    ${result.carb_target_g_per_hr} g/hr`);
  lines.push(`Total carbs:    ${result.total_carbs_g} g`);
  lines.push(`Fluid target:   ${result.fluid_ml_per_hr} ml/hr`);
  lines.push(`Sodium target:  ${result.sodium_mg_per_hr} mg/hr`);
  lines.push("");

  if (result.schedule.length > 0) {
    lines.push("INTAKE SCHEDULE");
    lines.push("-".repeat(30));
    result.schedule.forEach((item) => {
      lines.push(`${String(item.minute_offset).padStart(3, " ")} min  →  ${item.suggestion} (${item.carbs_g}g)`);
    });
    lines.push("Assumes ~25g carbs per gel; adjust to your products.");
    lines.push("");
  } else {
    lines.push("No in-session schedule required.");
    lines.push("");
  }

  if (result.caffeine_guidance) {
    lines.push("CAFFEINE");
    lines.push("-".repeat(30));
    lines.push(
      `${result.caffeine_guidance.range_mg[0]}–${result.caffeine_guidance.range_mg[1]} mg · ${result.caffeine_guidance.timing_text}`
    );
    result.caffeine_guidance.notes.forEach((n) => lines.push(`• ${n}`));
    lines.push("");
  }

  if (result.bicarb_protocol) {
    lines.push(`BICARB - ${result.bicarb_protocol.brand.toUpperCase()}`);
    lines.push("-".repeat(30));
    if (result.bicarb_protocol.dose_g !== undefined) {
      lines.push(`Dose: ${result.bicarb_protocol.dose_g} g`);
    }
    lines.push(`Timing: ${result.bicarb_protocol.timing_text}`);
    result.bicarb_protocol.cautions.forEach((c) => lines.push(`• ${c}`));
    lines.push("");
  }

  if (result.nomio_protocol) {
    lines.push("NOMIO");
    lines.push("-".repeat(30));
    lines.push(`Timing: ${result.nomio_protocol.timing_text}`);
    lines.push(result.nomio_protocol.serving_note);
    result.nomio_protocol.cautions.forEach((c) => lines.push(`• ${c}`));
    lines.push("");
  }

  lines.push("NOTES");
  lines.push("-".repeat(30));
  result.notes.forEach((n) => lines.push(`• ${n}`));
  lines.push("");
  lines.push("Generated by concept//fuel (conceptathletic.com/fuel)");

  return lines.join("\n");
}

export default function PlanResults({ result, planValues, onStartOver }: PlanResultsProps) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    const text = buildCopyText(result);
    try {
      await navigator.clipboard.writeText(text);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch {
      // Fallback
      const el = document.createElement("textarea");
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  return (
    <div>
      {/* Context bar */}
      {planValues && (
        <div
          style={{
            display: "flex",
            gap: "12px",
            flexWrap: "wrap",
            marginBottom: "24px",
            padding: "10px 14px",
            background: "var(--surface)",
            border: "1px solid var(--border)",
            borderRadius: "4px",
            fontSize: "12px",
            color: "var(--text-muted)",
          }}
        >
          <span>{{
            running: "Running",
            trail_running: "Trail Running",
            cycling: "Cycling",
            hyrox: "Hyrox",
          }[planValues.sport] ?? planValues.sport}</span>
          <span>·</span>
          <span style={{ textTransform: "capitalize" }}>{planValues.plan_type}</span>
          <span>·</span>
          <span style={{ textTransform: "capitalize" }}>{planValues.effort} effort</span>
          <span>·</span>
          <span>{planValues.duration} hr</span>
        </div>
      )}

      {/* Key warning */}
      <div
        style={{
          background: "rgba(255,255,255,0.03)",
          border: "1px solid var(--border)",
          borderRadius: "4px",
          padding: "12px 16px",
          marginBottom: "28px",
          display: "flex",
          alignItems: "flex-start",
          gap: "10px",
        }}
      >
        <span style={{ fontSize: "14px" }}>⚠</span>
        <p style={{ fontSize: "12px", color: "var(--text-muted)", lineHeight: 1.6 }}>
          <strong style={{ color: "var(--text)" }}>
            Practise this strategy in training before race day.
          </strong>{" "}
          These are evidence-informed starting points. Individual needs vary. See{" "}
          <a
            href="/disclaimer"
            style={{ color: "var(--accent-dim)", textDecoration: "none" }}
          >
            disclaimer
          </a>
          .
        </p>
      </div>

      {/* Key metrics */}
      <div style={{ marginBottom: "28px" }}>
        <SectionTitle>Key targets</SectionTitle>
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "repeat(auto-fit, minmax(140px, 1fr))",
            gap: "10px",
          }}
        >
          <MetricCard
            label="Carb target"
            value={`${result.carb_target_g_per_hr} g/hr`}
          />
          <MetricCard
            label="Total carbs"
            value={`${result.total_carbs_g} g`}
          />
          <MetricCard
            label="Fluid target"
            value={`${result.fluid_ml_per_hr} ml/hr`}
          />
          <MetricCard
            label="Sodium target"
            value={`${result.sodium_mg_per_hr} mg/hr`}
          />
        </div>
      </div>

      {/* Fun conversions */}
      {result.total_carbs_g > 0 && (() => {
        const gramsRice = Math.round(result.total_carbs_g * 100 / 28);
        const bowlsRice = (result.total_carbs_g / 50).toFixed(1);
        // Battersea Park outer loop ≈ 4km; at 5:00/km = 20 min = 1/3 hr
        const carbsPerLap = Math.round(result.carb_target_g_per_hr / 3);
        const lapsEquiv = carbsPerLap > 0 ? (result.total_carbs_g / carbsPerLap).toFixed(1) : "—";
        return (
          <div style={{ marginBottom: "28px" }}>
            <SectionTitle>in other words</SectionTitle>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
                gap: "10px",
              }}
            >
              <div
                style={{
                  background: "var(--surface)",
                  border: "1px solid var(--border)",
                  borderRadius: "4px",
                  padding: "16px",
                }}
              >
                <p
                  style={{
                    fontSize: "11px",
                    color: "var(--text-muted)",
                    marginBottom: "6px",
                    textTransform: "uppercase",
                    letterSpacing: "0.08em",
                  }}
                >
                  Rice equivalent
                </p>
                <p style={{ fontSize: "22px", fontWeight: 700, color: "var(--text)", lineHeight: 1.1 }}>
                  {gramsRice} g
                </p>
                <p style={{ fontSize: "11px", color: "var(--text-muted)", marginTop: "4px" }}>
                  {bowlsRice} bowls of cooked white rice
                </p>
                <p style={{ fontSize: "10px", color: "var(--text-muted)", marginTop: "6px", fontStyle: "italic" }}>
                  a nod to the marathon monks of Mt. Hiei
                </p>
              </div>

              <div
                style={{
                  background: "var(--surface)",
                  border: "1px solid var(--border)",
                  borderRadius: "4px",
                  padding: "16px",
                }}
              >
                <p
                  style={{
                    fontSize: "11px",
                    color: "var(--text-muted)",
                    marginBottom: "6px",
                    textTransform: "uppercase",
                    letterSpacing: "0.08em",
                  }}
                >
                  Battersea Park laps
                </p>
                <p style={{ fontSize: "22px", fontWeight: 700, color: "var(--text)", lineHeight: 1.1 }}>
                  {lapsEquiv}
                </p>
                <p style={{ fontSize: "11px", color: "var(--text-muted)", marginTop: "4px" }}>
                  laps of Battersea Park (4 km/lap, 5:00/km)
                </p>
                <p style={{ fontSize: "10px", color: "var(--text-muted)", marginTop: "6px" }}>
                  ~{carbsPerLap} g carbs per lap at your target rate
                </p>
              </div>
            </div>
          </div>
        );
      })()}

      {/* Schedule */}
      <div style={{ marginBottom: "28px" }}>
        <SectionTitle>Intake schedule</SectionTitle>
        {result.schedule.length > 0 ? (
          <>
            <div
              style={{
                border: "1px solid var(--border)",
                borderRadius: "4px",
                overflow: "hidden",
              }}
            >
              {result.schedule.map((item: ScheduleItem, i: number) => (
                <div
                  key={item.minute_offset}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "16px",
                    padding: "11px 16px",
                    borderBottom:
                      i < result.schedule.length - 1
                        ? "1px solid var(--border)"
                        : "none",
                    background:
                      i % 2 === 0 ? "var(--surface)" : "transparent",
                  }}
                >
                  <span
                    style={{
                      minWidth: "64px",
                      fontSize: "13px",
                      fontWeight: 700,
                      color: "var(--accent)",
                      fontVariantNumeric: "tabular-nums",
                    }}
                  >
                    {item.minute_offset} min
                  </span>
                  <span style={{ fontSize: "13px", color: "var(--text)", flex: 1 }}>
                    {item.suggestion}
                  </span>
                  <span
                    style={{
                      fontSize: "12px",
                      color: "var(--text-muted)",
                      fontVariantNumeric: "tabular-nums",
                    }}
                  >
                    {item.carbs_g} g
                  </span>
                </div>
              ))}
            </div>
            <p
              style={{
                fontSize: "11px",
                color: "var(--text-muted)",
                marginTop: "8px",
              }}
            >
              {result.notes[1]}
            </p>
          </>
        ) : (
          <div
            style={{
              padding: "16px",
              border: "1px solid var(--border)",
              borderRadius: "4px",
              background: "var(--surface)",
            }}
          >
            <p style={{ fontSize: "13px", color: "var(--text-muted)" }}>
              No in-session schedule needed for this duration/target. Focus on
              pre-session nutrition.
            </p>
          </div>
        )}
      </div>

      {/* Caffeine */}
      {result.caffeine_guidance && (
        <div style={{ marginBottom: "28px" }}>
          <SectionTitle>Caffeine guidance</SectionTitle>
          <div
            style={{
              border: "1px solid var(--border)",
              borderRadius: "4px",
              padding: "16px",
              background: "var(--surface)",
            }}
          >
            <p style={{ fontSize: "15px", fontWeight: 600, marginBottom: "6px" }}>
              {result.caffeine_guidance.range_mg[0]}–
              {result.caffeine_guidance.range_mg[1]} mg
            </p>
            <p style={{ fontSize: "13px", color: "var(--text-muted)", marginBottom: "12px" }}>
              {result.caffeine_guidance.timing_text}
            </p>
            <ul
              style={{
                listStyle: "none",
                padding: 0,
                margin: 0,
                display: "flex",
                flexDirection: "column",
                gap: "6px",
              }}
            >
              {result.caffeine_guidance.notes.map((note, i) => (
                <li
                  key={i}
                  style={{
                    fontSize: "12px",
                    color: "var(--text-muted)",
                    display: "flex",
                    gap: "8px",
                  }}
                >
                  <span style={{ color: "var(--text-muted)" }}>·</span>
                  {note}
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {/* Bicarb */}
      {result.bicarb_protocol && (
        <div style={{ marginBottom: "28px" }}>
          <SectionTitle>Bicarb protocol — {result.bicarb_protocol.brand}</SectionTitle>
          <div
            style={{
              border: "1px solid var(--border)",
              borderRadius: "4px",
              padding: "16px",
              background: "var(--surface)",
            }}
          >
            {result.bicarb_protocol.dose_g !== undefined && (
              <p style={{ fontSize: "15px", fontWeight: 600, marginBottom: "6px" }}>
                Dose: {result.bicarb_protocol.dose_g} g
              </p>
            )}
            <p style={{ fontSize: "13px", color: "var(--text-muted)", marginBottom: "12px" }}>
              {result.bicarb_protocol.timing_text}
            </p>
            <div
              style={{
                background: "rgba(255,68,68,0.07)",
                border: "1px solid rgba(255,68,68,0.2)",
                borderRadius: "4px",
                padding: "12px",
              }}
            >
              <p
                style={{
                  fontSize: "11px",
                  color: "var(--danger)",
                  marginBottom: "8px",
                  textTransform: "uppercase",
                  letterSpacing: "0.08em",
                  fontWeight: 600,
                }}
              >
                Important cautions
              </p>
              <ul
                style={{
                  listStyle: "none",
                  padding: 0,
                  margin: 0,
                  display: "flex",
                  flexDirection: "column",
                  gap: "6px",
                }}
              >
                {result.bicarb_protocol.cautions.map((c, i) => (
                  <li
                    key={i}
                    style={{
                      fontSize: "12px",
                      color: "var(--text-muted)",
                      display: "flex",
                      gap: "8px",
                    }}
                  >
                    <span>·</span>
                    {c}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* Nomio */}
      {result.nomio_protocol && (
        <div style={{ marginBottom: "28px" }}>
          <SectionTitle>Nomio protocol</SectionTitle>
          <div
            style={{
              border: "1px solid var(--border)",
              borderRadius: "4px",
              padding: "16px",
              background: "var(--surface)",
            }}
          >
            <p style={{ fontSize: "13px", color: "var(--text)", marginBottom: "12px", lineHeight: 1.6 }}>
              {result.nomio_protocol.timing_text}
            </p>
            <p style={{ fontSize: "12px", color: "var(--text-muted)", marginBottom: "12px" }}>
              {result.nomio_protocol.serving_note}
            </p>
            <div
              style={{
                background: "rgba(255,68,68,0.07)",
                border: "1px solid rgba(255,68,68,0.2)",
                borderRadius: "4px",
                padding: "12px",
              }}
            >
              <p
                style={{
                  fontSize: "11px",
                  color: "var(--danger)",
                  marginBottom: "8px",
                  textTransform: "uppercase",
                  letterSpacing: "0.08em",
                  fontWeight: 600,
                }}
              >
                Important cautions
              </p>
              <ul
                style={{
                  listStyle: "none",
                  padding: 0,
                  margin: 0,
                  display: "flex",
                  flexDirection: "column",
                  gap: "6px",
                }}
              >
                {result.nomio_protocol.cautions.map((c, i) => (
                  <li
                    key={i}
                    style={{
                      fontSize: "12px",
                      color: "var(--text-muted)",
                      display: "flex",
                      gap: "8px",
                    }}
                  >
                    <span>·</span>
                    {c}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* Notes */}
      <div style={{ marginBottom: "36px" }}>
        <SectionTitle>Notes</SectionTitle>
        <ul
          style={{
            listStyle: "none",
            padding: 0,
            margin: 0,
            display: "flex",
            flexDirection: "column",
            gap: "8px",
          }}
        >
          {result.notes.map((note, i) => (
            <li
              key={i}
              style={{
                fontSize: "13px",
                color: "var(--text-muted)",
                display: "flex",
                gap: "10px",
                lineHeight: 1.6,
              }}
            >
              <span style={{ color: "var(--text-muted)", flexShrink: 0 }}>·</span>
              {note}
            </li>
          ))}
        </ul>
      </div>

      {/* Actions */}
      <div
        style={{
          display: "flex",
          gap: "12px",
          paddingTop: "20px",
          borderTop: "1px solid var(--border)",
          flexWrap: "wrap",
        }}
      >
        <button
          onClick={handleCopy}
          style={{
            padding: "12px 24px",
            background: copied ? "rgba(68,255,136,0.15)" : "var(--surface-2)",
            color: copied ? "var(--success)" : "var(--text)",
            fontWeight: 600,
            fontSize: "14px",
            borderRadius: "4px",
            border: `1px solid ${copied ? "var(--success)" : "var(--border)"}`,
            cursor: "pointer",
            transition: "all 0.2s",
          }}
        >
          {copied ? "✓ Copied!" : "Copy plan"}
        </button>
        <button
          onClick={onStartOver}
          style={{
            padding: "12px 24px",
            background: "transparent",
            color: "var(--text-muted)",
            fontWeight: 500,
            fontSize: "14px",
            borderRadius: "4px",
            border: "1px solid var(--border)",
            cursor: "pointer",
          }}
        >
          Start over
        </button>
      </div>
    </div>
  );
}
