"use client";

import { useState, useEffect } from "react";
import type { FuelPlanOutput, ScheduleItem } from "@/lib/fuelEngine";
import { addFuelPlanToCalendar } from "@/lib/calendar";
import { parseDurationToMinutes } from "@/lib/fuelEngine";

interface PlanResultsProps {
  result: FuelPlanOutput;
  planValues: {
    plan_type: string;
    sport: string;
    effort: string;
    duration: string;
    race_name?: string;
    session_name?: string;
    subtitle?: string;
  } | null;
  name?: string;
  onStartOver: () => void;
}

function MetricCard({
  label,
  value,
  sub,
}: {
  label: string;
  value: string;
  sub?: string;
}) {
  return (
    <div
      style={{
        background: "var(--surface-2)",
        border: "1px solid var(--border)",
        borderRadius: "4px",
        padding: "16px",
      }}
    >
      <p
        style={{
          fontSize: "11px",
          color: "var(--text-muted)",
          marginBottom: "6px",
          textTransform: "uppercase",
          letterSpacing: "0.08em",
        }}
      >
        {label}
      </p>
      <p style={{ fontSize: "22px", fontWeight: 700, color: "var(--text)", lineHeight: 1.1 }}>
        {value}
      </p>
      {sub && (
        <p style={{ fontSize: "11px", color: "var(--text-muted)", marginTop: "4px" }}>
          {sub}
        </p>
      )}
    </div>
  );
}

function SectionTitle({ children }: { children: React.ReactNode }) {
  return (
    <p
      style={{
        fontSize: "11px",
        color: "var(--text-muted)",
        letterSpacing: "0.1em",
        textTransform: "uppercase",
        marginBottom: "12px",
        paddingBottom: "8px",
        borderBottom: "1px solid var(--border)",
      }}
    >
      {children}
    </p>
  );
}

function buildCopyText(result: FuelPlanOutput): string {
  const lines: string[] = [];
  lines.push("concept//fuel - Fuel Plan");
  lines.push("=".repeat(40));
  lines.push(`Carb target:    ${result.carb_target_g_per_hr} g/hr`);
  lines.push(`Total carbs:    ${result.total_carbs_g} g`);
  lines.push(`Fluid target:   ${result.fluid_ml_per_hr} ml/hr`);
  lines.push(`Sodium target:  ${result.sodium_mg_per_hr} mg/hr`);
  lines.push("");

  if (result.schedule.length > 0) {
    lines.push("INTAKE SCHEDULE");
    lines.push("-".repeat(30));
    result.schedule.forEach((item) => {
      const label = item.minute_offset === 0 ? "Pre-start" : `${item.minute_offset} min`;
      lines.push(`${label.padStart(10, " ")}  →  ${item.suggestion} (${item.carbs_g}g)`);
    });
    lines.push("");
  } else {
    lines.push("No in-session schedule required.");
    lines.push("");
  }

  if (result.caffeine_guidance) {
    lines.push("CAFFEINE");
    lines.push("-".repeat(30));
    lines.push(
      `${result.caffeine_guidance.range_mg[0]}–${result.caffeine_guidance.range_mg[1]} mg · ${result.caffeine_guidance.timing_text}`
    );
    result.caffeine_guidance.notes.forEach((n) => lines.push(`• ${n}`));
    lines.push("");
  }

  if (result.bicarb_protocol) {
    lines.push(`BICARB - ${result.bicarb_protocol.brand.toUpperCase()}`);
    lines.push("-".repeat(30));
    if (result.bicarb_protocol.dose_g !== undefined) {
      lines.push(`Dose: ${result.bicarb_protocol.dose_g} g`);
    }
    lines.push(`Timing: ${result.bicarb_protocol.timing_text}`);
    result.bicarb_protocol.cautions.forEach((c) => lines.push(`• ${c}`));
    lines.push("");
  }

  if (result.nomio_protocol) {
    lines.push("NOMIO");
    lines.push("-".repeat(30));
    lines.push(`Timing: ${result.nomio_protocol.timing_text}`);
    lines.push(result.nomio_protocol.serving_note);
    result.nomio_protocol.cautions.forEach((c) => lines.push(`• ${c}`));
    lines.push("");
  }

  lines.push("NOTES");
  lines.push("-".repeat(30));
  result.notes.forEach((n) => lines.push(`• ${n}`));
  lines.push("");
  lines.push("Generated by concept//fuel — conceptathletic.com/fuel");

  return lines.join("\n");
}

// ─── SHARE CARD CANVAS ────────────────────────────────────────────────────────

const CANVAS_THEMES = {
  dark:  { bg: "#0a0a0a", surface: "#111111", surface2: "#1a1a1a", border: "#2a2a2a", text: "#f0f0f0", muted: "#888888", dimmed: "#555555", rowA: "#111111", rowB: "#0e0e0e", grid: "rgba(255,255,255,0.04)" },
  light: { bg: "#f5f2ed", surface: "#ede9e3", surface2: "#e5e0d9", border: "#ccc8c0", text: "#1a1714", muted: "#7a7570", dimmed: "#999999", rowA: "#e8e4de", rowB: "#e3dfd9", grid: "rgba(0,0,0,0.03)" },
  sage:  { bg: "#edf0eb", surface: "#e3e7de", surface2: "#d7dcd1", border: "#b4bcac", text: "#1c2418", muted: "#627060", dimmed: "#8a9e88", rowA: "#dde1d8", rowB: "#d8dcd3", grid: "rgba(0,0,0,0.03)" },
  mocha: { bg: "#f2ede6", surface: "#e8e0d5", surface2: "#ddd4c5", border: "#c2b4a0", text: "#2c1f14", muted: "#7d6858", dimmed: "#a09080", rowA: "#e2d9cc", rowB: "#ddd4c7", grid: "rgba(0,0,0,0.03)" },
};

function getCanvasTheme() {
  const t = typeof localStorage !== "undefined" ? (localStorage.getItem("cf_theme") ?? "dark") : "dark";
  return CANVAS_THEMES[t as keyof typeof CANVAS_THEMES] ?? CANVAS_THEMES.dark;
}

function buildShareCanvas(
  result: FuelPlanOutput,
  planValues: PlanResultsProps["planValues"]
): HTMLCanvasElement {
  // Instagram Story dimensions
  const W = 1080;
  const H = 1920;
  const M = 90; // margin
  const canvas = document.createElement("canvas");
  canvas.width = W;
  canvas.height = H;
  const ctx = canvas.getContext("2d")!;
  const T = getCanvasTheme();
  const FONT = "'ui-monospace', 'Cascadia Code', 'Fira Mono', monospace";

  // ── Helpers ──────────────────────────────────────────────────────────────────

  function rule(y: number, alpha = 1) {
    ctx.save();
    ctx.globalAlpha = alpha;
    ctx.strokeStyle = T.border;
    ctx.lineWidth = 1;
    ctx.beginPath(); ctx.moveTo(M, y); ctx.lineTo(W - M, y); ctx.stroke();
    ctx.restore();
  }

  function igIcon(x: number, y: number, size: number) {
    const r2 = size * 0.22; const s2 = size;
    ctx.fillStyle = T.muted;
    ctx.beginPath();
    ctx.moveTo(x + r2, y); ctx.lineTo(x + s2 - r2, y);
    ctx.quadraticCurveTo(x + s2, y, x + s2, y + r2);
    ctx.lineTo(x + s2, y + s2 - r2);
    ctx.quadraticCurveTo(x + s2, y + s2, x + s2 - r2, y + s2);
    ctx.lineTo(x + r2, y + s2);
    ctx.quadraticCurveTo(x, y + s2, x, y + s2 - r2);
    ctx.lineTo(x, y + r2);
    ctx.quadraticCurveTo(x, y, x + r2, y);
    ctx.closePath();
    ctx.fill();
    ctx.fillStyle = T.bg;
    ctx.beginPath(); ctx.arc(x + s2 / 2, y + s2 / 2, s2 * 0.27, 0, Math.PI * 2); ctx.fill();
    ctx.fillStyle = T.muted;
    ctx.beginPath(); ctx.arc(x + s2 - s2 * 0.22, y + s2 * 0.22, s2 * 0.1, 0, Math.PI * 2); ctx.fill();
    ctx.strokeStyle = T.bg;
    ctx.lineWidth = s2 * 0.08;
    ctx.beginPath(); ctx.arc(x + s2 / 2, y + s2 / 2, s2 * 0.27 + s2 * 0.06, 0, Math.PI * 2); ctx.stroke();
  }

  // ── Background ───────────────────────────────────────────────────────────────
  ctx.fillStyle = T.bg;
  ctx.fillRect(0, 0, W, H);

  // Subtle grid
  ctx.strokeStyle = T.grid;
  ctx.lineWidth = 1;
  for (let x = 0; x < W; x += 90) { ctx.beginPath(); ctx.moveTo(x, 0); ctx.lineTo(x, H); ctx.stroke(); }
  for (let y = 0; y < H; y += 90) { ctx.beginPath(); ctx.moveTo(0, y); ctx.lineTo(W, y); ctx.stroke(); }

  // ── Brand mark ───────────────────────────────────────────────────────────────
  ctx.font = `bold 20px ${FONT}`;
  ctx.fillStyle = T.text;
  ctx.fillText("concept", M, 82);
  ctx.fillStyle = T.muted;
  ctx.fillText("//", M + ctx.measureText("concept").width, 82);
  ctx.fillStyle = T.text;
  ctx.fillText("fuel", M + ctx.measureText("concept//").width, 82);

  // Sport / effort tag top-right
  if (planValues) {
    const sportLabel: Record<string, string> = { running: "Running", trail_running: "Trail", cycling: "Cycling", hyrox: "Hyrox" };
    const effortLabel: Record<string, string> = { easy: "Easy", steady: "Steady", hard: "Hard", race: "Race effort" };
    const tag = [sportLabel[planValues.sport] ?? planValues.sport, effortLabel[planValues.effort] ?? ""].filter(Boolean).join(" · ");
    ctx.font = `13px ${FONT}`;
    ctx.fillStyle = T.dimmed;
    ctx.textAlign = "right";
    ctx.fillText(tag, W - M, 82);
    ctx.textAlign = "left";
  }

  rule(110);

  // ── Hero: race/session name ───────────────────────────────────────────────────
  let heroName = "";
  let heroSub = "";
  if (planValues) {
    if (planValues.plan_type === "race") {
      heroName = planValues.race_name || "Fuel plan";
      heroSub = planValues.subtitle ? `${planValues.subtitle} · race day` : "race day";
    } else {
      heroName = planValues.session_name || "Training session";
      heroSub = [planValues.subtitle, planValues.sport !== "running" ? planValues.sport : ""].filter(Boolean).join(" · ");
    }
  }

  // Hero name — large, wrap if needed
  ctx.font = `bold 80px ${FONT}`;
  ctx.fillStyle = T.text;
  const heroWords = heroName.split(" ");
  let heroLine = "";
  let heroY = 210;
  for (const word of heroWords) {
    const test = heroLine ? heroLine + " " + word : word;
    if (ctx.measureText(test).width > W - M * 2 && heroLine) {
      ctx.fillText(heroLine, M, heroY);
      heroLine = word;
      heroY += 92;
    } else { heroLine = test; }
  }
  ctx.fillText(heroLine, M, heroY);
  heroY += 56;

  // Subtitle
  if (heroSub) {
    ctx.font = `22px ${FONT}`;
    ctx.fillStyle = T.muted;
    ctx.fillText(heroSub, M, heroY);
    heroY += 44;
  }

  const postHeroY = heroY + 32;
  rule(postHeroY);

  // ── Carbohydrate target ───────────────────────────────────────────────────────
  const carbSectionY = postHeroY + 60;
  ctx.font = `11px ${FONT}`;
  ctx.fillStyle = T.dimmed;
  ctx.letterSpacing = "0.14em";
  ctx.fillText("CARBOHYDRATE TARGET", M, carbSectionY);
  ctx.letterSpacing = "0px";

  ctx.font = `bold 160px ${FONT}`;
  ctx.fillStyle = T.text;
  ctx.fillText(`${result.carb_target_g_per_hr}`, M, carbSectionY + 168);

  ctx.font = `bold 30px ${FONT}`;
  ctx.fillStyle = T.muted;
  ctx.fillText("g / hr", M, carbSectionY + 216);

  const postCarbY = carbSectionY + 260;
  rule(postCarbY);

  // ── 2×2 metric grid ──────────────────────────────────────────────────────────
  const gridTop = postCarbY + 50;
  const cellW = (W - M * 2 - 12) / 2;
  const cellH = 160;
  const metrics = [
    { label: "TOTAL CARBS",   value: `${result.total_carbs_g}g` },
    { label: "FLUID",         value: `${result.fluid_ml_per_hr}ml/hr` },
    { label: "SODIUM",        value: `${result.sodium_mg_per_hr}mg/hr` },
    { label: "DURATION",      value: planValues?.duration ?? "—" },
  ];
  metrics.forEach((m, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const cx = M + col * (cellW + 12);
    const cy = gridTop + row * (cellH + 12);
    ctx.fillStyle = T.surface;
    ctx.strokeStyle = T.border;
    ctx.lineWidth = 1;
    ctx.fillRect(cx, cy, cellW, cellH);
    ctx.strokeRect(cx, cy, cellW, cellH);
    ctx.font = `11px ${FONT}`;
    ctx.fillStyle = T.dimmed;
    ctx.fillText(m.label, cx + 20, cy + 30);
    ctx.font = `bold 36px ${FONT}`;
    ctx.fillStyle = T.text;
    ctx.fillText(m.value, cx + 20, cy + 110);
  });

  const postGridY = gridTop + 2 * cellH + 12 + 50;
  rule(postGridY);

  // ── Caffeine (if present) ─────────────────────────────────────────────────────
  let postCafY = postGridY + 50;
  if (result.caffeine_guidance) {
    ctx.font = `11px ${FONT}`;
    ctx.fillStyle = T.dimmed;
    ctx.fillText("CAFFEINE", M, postCafY);
    ctx.font = `bold 28px ${FONT}`;
    ctx.fillStyle = T.text;
    ctx.fillText(
      `${result.caffeine_guidance.range_mg[0]}–${result.caffeine_guidance.range_mg[1]} mg`,
      M, postCafY + 40
    );
    ctx.font = `16px ${FONT}`;
    ctx.fillStyle = T.muted;
    ctx.fillText(result.caffeine_guidance.timing_text, M, postCafY + 74);
    postCafY += 110;
    rule(postCafY);
    postCafY += 50;
  }

  // ── Protocol label ────────────────────────────────────────────────────────────
  ctx.font = `11px ${FONT}`;
  ctx.fillStyle = T.dimmed;
  ctx.fillText("PROTOCOL", M, postCafY);
  ctx.font = `20px ${FONT}`;
  ctx.fillStyle = T.muted;
  ctx.fillText(result.protocol_name, M, postCafY + 34);

  // ── Footer ────────────────────────────────────────────────────────────────────
  const footerY = H - 90;
  rule(footerY);

  ctx.font = `14px ${FONT}`;
  ctx.fillStyle = T.dimmed;
  ctx.fillText("conceptclub.co.uk/plan", M, H - 42);

  // IG icon + handle
  const igSize = 18;
  const igLabel = "@conceptathletic";
  ctx.font = `14px ${FONT}`;
  const igLabelW = ctx.measureText(igLabel).width;
  const igX = W - M - igSize - 8 - igLabelW;
  igIcon(igX, H - 42 - igSize + 4, igSize);
  ctx.fillStyle = T.muted;
  ctx.fillText(igLabel, igX + igSize + 8, H - 42);

  return canvas;
}

// ─── NETLIFY FORM SUBMIT ──────────────────────────────────────────────────────

async function submitNetlifyForm(formName: string, data: Record<string, string>) {
  try {
    await fetch("/netlify-forms.html", {
      method: "POST",
      headers: { "Content-Type": "application/x-www-form-urlencoded" },
      body: new URLSearchParams({ "form-name": formName, ...data }).toString(),
    });
  } catch {
    // Silently fail — tracking is best-effort
  }
}

// ─── SAVE PLAN FORM ───────────────────────────────────────────────────────────

function SavePlanForm({
  result,
  planValues,
  name,
}: {
  result: FuelPlanOutput;
  planValues: PlanResultsProps["planValues"] | null;
  name?: string;
}) {
  const [email, setEmail] = useState("");
  const [status, setStatus] = useState<"idle" | "sending" | "sent" | "error">("idle");

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!email.trim()) return;
    setStatus("sending");
    try {
      await submitNetlifyForm("save_plan", {
        email: email.trim(),
        name: name ?? "",
        sport: planValues?.sport ?? "",
        plan_type: planValues?.plan_type ?? "",
        effort: planValues?.effort ?? "",
        duration: planValues?.duration ?? "",
        carb_target_g_per_hr: String(result.carb_target_g_per_hr),
        total_carbs_g: String(result.total_carbs_g),
        fluid_ml_per_hr: String(result.fluid_ml_per_hr),
        sodium_mg_per_hr: String(result.sodium_mg_per_hr),
      });
      setStatus("sent");
    } catch {
      setStatus("error");
    }
  };

  if (status === "sent") {
    return (
      <div
        style={{
          padding: "16px",
          background: "rgba(68,255,136,0.07)",
          border: "1px solid rgba(68,255,136,0.25)",
          borderRadius: "4px",
          fontSize: "13px",
          color: "var(--success)",
        }}
      >
        ✓ Plan saved — we&apos;ll keep a copy for you.
      </div>
    );
  }

  return (
    <form onSubmit={handleSave} style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
      <input
        type="email"
        placeholder="your@email.com"
        value={email}
        onChange={(e) => setEmail(e.target.value)}
        required
        style={{ flex: "1 1 200px", minWidth: "0" }}
      />
      <button
        type="submit"
        disabled={status === "sending"}
        style={{
          padding: "8px 20px",
          background: "var(--accent)",
          color: "var(--bg)",
          fontWeight: 600,
          fontSize: "13px",
          borderRadius: "4px",
          border: "none",
          cursor: status === "sending" ? "wait" : "pointer",
          whiteSpace: "nowrap",
        }}
      >
        {status === "sending" ? "Saving…" : "Save plan →"}
      </button>
      {status === "error" && (
        <p style={{ width: "100%", fontSize: "12px", color: "var(--danger)", margin: 0 }}>
          Something went wrong. Try copying the plan instead.
        </p>
      )}
    </form>
  );
}

// ─── SHARE SECTION ────────────────────────────────────────────────────────────

function ShareSection({
  result,
  planValues,
}: {
  result: FuelPlanOutput;
  planValues: PlanResultsProps["planValues"] | null;
}) {
  const [copied, setCopied] = useState(false);
  const [downloading, setDownloading] = useState(false);
  const [canShare] = useState(() => typeof navigator !== "undefined" && !!navigator.share);

  const shareText = `My race fuel plan from concept//fuel:\n\n${result.carb_target_g_per_hr}g/hr carbs · ${result.total_carbs_g}g total · ${result.fluid_ml_per_hr}ml/hr fluid\n\nGenerate yours → conceptathletic.com/fuel`;

  const handleCopy = async () => {
    const text = buildCopyText(result);
    try {
      await navigator.clipboard.writeText(text);
    } catch {
      const el = document.createElement("textarea");
      el.value = text;
      document.body.appendChild(el);
      el.select();
      document.execCommand("copy");
      document.body.removeChild(el);
    }
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleDownload = async () => {
    setDownloading(true);
    try {
      const canvas = buildShareCanvas(result, planValues);
      const link = document.createElement("a");
      link.download = "concept-fuel-plan.png";
      link.href = canvas.toDataURL("image/png");
      link.click();
    } finally {
      setDownloading(false);
    }
  };

  const handleNativeShare = async () => {
    try {
      const canvas = buildShareCanvas(result, planValues);
      canvas.toBlob(async (blob) => {
        if (!blob) return;
        const file = new File([blob], "fuel-plan.png", { type: "image/png" });
        const shareData: ShareData = {
          title: "My fuel plan — concept//fuel",
          text: shareText,
          files: [file],
        };
        if (navigator.canShare && navigator.canShare(shareData)) {
          await navigator.share(shareData);
        } else {
          // Fall back to text-only share
          await navigator.share({ title: "My fuel plan — concept//fuel", text: shareText });
        }
      }, "image/png");
    } catch {
      // User cancelled or not supported
    }
  };

  const handleAddToCalendar = () => {
    const eventName = planValues?.race_name ?? planValues?.session_name ?? "Training session";
    const durationMinutes = planValues?.duration ? parseDurationToMinutes(planValues.duration) : 60;
    addFuelPlanToCalendar({
      eventName,
      durationMinutes,
      carbGPerHr:    result.carb_target_g_per_hr,
      fluidMlPerHr:  result.fluid_ml_per_hr,
      intakeSchedule: result.schedule,
    });
  };

  const whatsappUrl = `https://wa.me/?text=${encodeURIComponent(shareText)}`;
  const twitterUrl = `https://x.com/intent/tweet?text=${encodeURIComponent(shareText)}`;

  const btnStyle = (primary = false): React.CSSProperties => ({
    padding: "10px 18px",
    background: primary ? "var(--accent)" : "var(--surface-2)",
    color: primary ? "var(--bg)" : "var(--text)",
    fontWeight: 600,
    fontSize: "13px",
    borderRadius: "4px",
    border: `1px solid ${primary ? "transparent" : "var(--border)"}`,
    cursor: "pointer",
    textDecoration: "none",
    display: "inline-flex",
    alignItems: "center",
    gap: "6px",
    whiteSpace: "nowrap" as const,
  });

  return (
    <div>
      <SectionTitle>Share your plan</SectionTitle>

      {/* Primary share buttons */}
      <div style={{ display: "flex", gap: "10px", flexWrap: "wrap", marginBottom: "10px" }}>
        {canShare && (
          <button onClick={handleNativeShare} style={btnStyle(true)}>
            ↑ Share (Instagram / WhatsApp / TikTok…)
          </button>
        )}
        <button onClick={handleDownload} disabled={downloading} style={btnStyle()}>
          {downloading ? "Generating…" : "↓ Download card"}
        </button>
        <button
          onClick={handleCopy}
          style={{
            ...btnStyle(),
            background: copied ? "rgba(68,255,136,0.1)" : "var(--surface-2)",
            color: copied ? "var(--success)" : "var(--text)",
            border: `1px solid ${copied ? "rgba(68,255,136,0.3)" : "var(--border)"}`,
          }}
        >
          {copied ? "✓ Copied!" : "Copy text"}
        </button>
        <button onClick={handleAddToCalendar} style={btnStyle()}>
          + Add to calendar
        </button>
      </div>

      {/* Social links */}
      <div style={{ display: "flex", gap: "8px", flexWrap: "wrap" }}>
        <a href={whatsappUrl} target="_blank" rel="noopener noreferrer" style={btnStyle()}>
          WhatsApp
        </a>
        <a href={twitterUrl} target="_blank" rel="noopener noreferrer" style={btnStyle()}>
          X / Twitter
        </a>
        {!canShare && (
          <p style={{ fontSize: "12px", color: "var(--text-muted)", margin: "auto 0" }}>
            On mobile: use &ldquo;Share&rdquo; to post directly to Instagram or TikTok.
          </p>
        )}
      </div>
    </div>
  );
}

// ─── MAIN COMPONENT ───────────────────────────────────────────────────────────

export default function PlanResults({ result, planValues, name, onStartOver }: PlanResultsProps) {
  // Fire usage tracking once when plan first renders
  useEffect(() => {
    const accessCode = typeof window !== "undefined"
      ? localStorage.getItem("cf_access_code") ?? "unknown"
      : "unknown";
    submitNetlifyForm("plan_usage", {
      sport: planValues?.sport ?? "",
      plan_type: planValues?.plan_type ?? "",
      effort: planValues?.effort ?? "",
      duration_minutes: planValues?.duration ?? "",
      carb_target_g_per_hr: String(result.carb_target_g_per_hr),
      access_code: accessCode,
      name: name ?? "",
    });
  // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  return (
    <div>
      {/* Personalised greeting */}
      {name && (
        <div style={{ marginBottom: "20px" }}>
          <h2
            style={{
              fontSize: "20px",
              fontWeight: 700,
              letterSpacing: "-0.02em",
              color: "var(--text)",
            }}
          >
            Hi {name}, here is your fuelling plan.
          </h2>
        </div>
      )}

      {/* Protocol name */}
      {result.protocol_name && (
        <div style={{ marginBottom: "8px" }}>
          <p
            style={{
              fontSize: "11px",
              color: "var(--text-muted)",
              letterSpacing: "0.12em",
              textTransform: "uppercase",
              marginBottom: "4px",
            }}
          >
            Protocol
          </p>
          <p
            style={{
              fontSize: "20px",
              fontWeight: 700,
              letterSpacing: "-0.03em",
              color: "var(--text)",
              marginBottom: "16px",
            }}
          >
            {result.protocol_name}
          </p>
        </div>
      )}

      {/* Context bar */}
      {planValues && (
        <div
          style={{
            display: "flex",
            gap: "12px",
            flexWrap: "wrap",
            marginBottom: "24px",
            padding: "10px 14px",
            background: "var(--surface)",
            border: "1px solid var(--border)",
            borderRadius: "4px",
            fontSize: "12px",
            color: "var(--text-muted)",
          }}
        >
          {planValues.plan_type === "race" ? (
            <>
              {planValues.race_name && <><span style={{ color: "var(--text)", fontWeight: 600 }}>{planValues.race_name}</span><span>·</span></>}
              {planValues.subtitle && <><span>{planValues.subtitle}</span><span>·</span></>}
              <span>Fuel for race</span>
              <span>·</span>
              <span style={{ textTransform: "capitalize" }}>{planValues.effort} effort</span>
              <span>·</span>
              <span>{planValues.duration} hr</span>
            </>
          ) : (
            <>
              {planValues.session_name && <><span style={{ color: "var(--text)", fontWeight: 600 }}>{planValues.session_name}</span><span>·</span></>}
              <span>{{
                running: "Running",
                trail_running: "Trail Running",
                cycling: "Cycling",
                hyrox: "Hyrox",
              }[planValues.sport] ?? planValues.sport}</span>
              {planValues.subtitle && <><span>·</span><span>{planValues.subtitle}</span></>}
              <span>·</span>
              <span style={{ textTransform: "capitalize" }}>{planValues.effort} effort</span>
              <span>·</span>
              <span>{planValues.duration} hr</span>
            </>
          )}
        </div>
      )}

      {/* Key warning */}
      <div
        style={{
          background: "rgba(255,255,255,0.03)",
          border: "1px solid var(--border)",
          borderRadius: "4px",
          padding: "12px 16px",
          marginBottom: "28px",
          display: "flex",
          alignItems: "flex-start",
          gap: "10px",
        }}
      >
        <span style={{ fontSize: "14px" }}>⚠</span>
        <p style={{ fontSize: "12px", color: "var(--text-muted)", lineHeight: 1.6 }}>
          <strong style={{ color: "var(--text)" }}>
            Practise this strategy in training before race day.
          </strong>{" "}
          These are evidence-informed starting points. Individual needs vary. See{" "}
          <a
            href="/disclaimer"
            style={{ color: "var(--accent-dim)", textDecoration: "none" }}
          >
            disclaimer
          </a>
          .
        </p>
      </div>

      {/* Key metrics */}
      <div style={{ marginBottom: "28px" }}>
        <SectionTitle>Key targets</SectionTitle>
        <div className="cf-metric-grid">
          <MetricCard
            label="Carb target"
            value={`${result.carb_target_g_per_hr} g/hr`}
          />
          <MetricCard
            label="Total carbs"
            value={`${result.total_carbs_g} g`}
          />
          <MetricCard
            label="Fluid target"
            value={`${result.fluid_ml_per_hr} ml/hr`}
          />
          <MetricCard
            label="Sodium target"
            value={`${result.sodium_mg_per_hr} mg/hr`}
          />
        </div>
      </div>

      {/* Fun conversions */}
      {result.total_carbs_g > 0 && (() => {
        const gramsRice = Math.round(result.total_carbs_g * 100 / 28);
        const bowlsRice = (result.total_carbs_g / 50).toFixed(1);
        const carbsPerLap = Math.round(result.carb_target_g_per_hr * 0.225);
        const lapsEquiv = carbsPerLap > 0 ? (result.total_carbs_g / carbsPerLap).toFixed(1) : "—";
        return (
          <div style={{ marginBottom: "28px" }}>
            <SectionTitle>in other words</SectionTitle>
            <div
              style={{
                display: "grid",
                gridTemplateColumns: "repeat(auto-fit, minmax(180px, 1fr))",
                gap: "10px",
              }}
            >
              <div
                style={{
                  background: "var(--surface)",
                  border: "1px solid var(--border)",
                  borderRadius: "4px",
                  padding: "16px",
                }}
              >
                <p style={{ fontSize: "11px", color: "var(--text-muted)", marginBottom: "6px", textTransform: "uppercase", letterSpacing: "0.08em" }}>
                  Rice equivalent
                </p>
                <p style={{ fontSize: "22px", fontWeight: 700, color: "var(--text)", lineHeight: 1.1 }}>
                  {gramsRice} g
                </p>
                <p style={{ fontSize: "11px", color: "var(--text-muted)", marginTop: "4px" }}>
                  {bowlsRice} bowls of cooked white rice
                </p>
              </div>

              <div
                style={{
                  background: "var(--surface)",
                  border: "1px solid var(--border)",
                  borderRadius: "4px",
                  padding: "16px",
                }}
              >
                <p style={{ fontSize: "11px", color: "var(--text-muted)", marginBottom: "6px", textTransform: "uppercase", letterSpacing: "0.08em" }}>
                  Battersea Park laps
                </p>
                <p style={{ fontSize: "22px", fontWeight: 700, color: "var(--text)", lineHeight: 1.1 }}>
                  {lapsEquiv}
                </p>
                <p style={{ fontSize: "11px", color: "var(--text-muted)", marginTop: "4px" }}>
                  laps of Battersea Park (2.7 km/lap, 5:00/km)
                </p>
                <p style={{ fontSize: "10px", color: "var(--text-muted)", marginTop: "6px" }}>
                  ~{carbsPerLap} g carbs per lap at your target rate
                </p>
              </div>
            </div>
          </div>
        );
      })()}

      {/* Schedule */}
      <div style={{ marginBottom: "28px" }}>
        <SectionTitle>Intake schedule</SectionTitle>
        {result.schedule.length > 0 ? (
          <>
            <div
              style={{
                border: "1px solid var(--border)",
                borderRadius: "4px",
                overflow: "hidden",
              }}
            >
              {result.schedule.map((item: ScheduleItem, i: number) => (
                <div
                  key={item.minute_offset}
                  style={{
                    display: "flex",
                    alignItems: "center",
                    gap: "16px",
                    padding: "11px 16px",
                    borderBottom:
                      i < result.schedule.length - 1
                        ? "1px solid var(--border)"
                        : "none",
                    background:
                      i % 2 === 0 ? "var(--surface)" : "transparent",
                  }}
                >
                  <span
                    style={{
                      minWidth: "64px",
                      fontSize: "13px",
                      fontWeight: 700,
                      color: "var(--accent)",
                      fontVariantNumeric: "tabular-nums",
                    }}
                  >
                    {item.minute_offset === 0 ? "Pre-start" : `${item.minute_offset} min`}
                  </span>
                  <span style={{ fontSize: "13px", color: "var(--text)", flex: 1 }}>
                    {item.suggestion}
                  </span>
                  <span
                    style={{
                      fontSize: "12px",
                      color: "var(--text-muted)",
                      fontVariantNumeric: "tabular-nums",
                    }}
                  >
                    {item.carbs_g} g
                  </span>
                </div>
              ))}
            </div>
            <p style={{ fontSize: "11px", color: "var(--text-muted)", marginTop: "8px" }}>
              {result.notes[1]}
            </p>
          </>
        ) : (
          <div
            style={{
              padding: "16px",
              border: "1px solid var(--border)",
              borderRadius: "4px",
              background: "var(--surface)",
            }}
          >
            <p style={{ fontSize: "13px", color: "var(--text-muted)" }}>
              No in-session schedule needed for this duration/target. Focus on
              pre-session nutrition.
            </p>
          </div>
        )}
      </div>

      {/* Caffeine */}
      {result.caffeine_guidance && (
        <div style={{ marginBottom: "28px" }}>
          <SectionTitle>Caffeine guidance</SectionTitle>
          <div
            style={{
              border: "1px solid var(--border)",
              borderRadius: "4px",
              padding: "16px",
              background: "var(--surface)",
            }}
          >
            <p style={{ fontSize: "15px", fontWeight: 600, marginBottom: "6px" }}>
              {result.caffeine_guidance.range_mg[0]}–
              {result.caffeine_guidance.range_mg[1]} mg
            </p>
            <p style={{ fontSize: "13px", color: "var(--text-muted)", marginBottom: "12px" }}>
              {result.caffeine_guidance.timing_text}
            </p>
            <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "6px" }}>
              {result.caffeine_guidance.notes.map((note, i) => (
                <li key={i} style={{ fontSize: "12px", color: "var(--text-muted)", display: "flex", gap: "8px" }}>
                  <span style={{ color: "var(--text-muted)" }}>·</span>
                  {note}
                </li>
              ))}
            </ul>
          </div>
        </div>
      )}

      {/* Bicarb */}
      {result.bicarb_protocol && (
        <div style={{ marginBottom: "28px" }}>
          <SectionTitle>Bicarb protocol — {result.bicarb_protocol.brand}</SectionTitle>
          <div
            style={{
              border: "1px solid var(--border)",
              borderRadius: "4px",
              padding: "16px",
              background: "var(--surface)",
            }}
          >
            {result.bicarb_protocol.dose_g !== undefined && (
              <p style={{ fontSize: "15px", fontWeight: 600, marginBottom: "6px" }}>
                Dose: {result.bicarb_protocol.dose_g} g
              </p>
            )}
            <p style={{ fontSize: "13px", color: "var(--text-muted)", marginBottom: "12px" }}>
              {result.bicarb_protocol.timing_text}
            </p>
            <div
              style={{
                background: "rgba(255,68,68,0.07)",
                border: "1px solid rgba(255,68,68,0.2)",
                borderRadius: "4px",
                padding: "12px",
              }}
            >
              <p style={{ fontSize: "11px", color: "var(--danger)", marginBottom: "8px", textTransform: "uppercase", letterSpacing: "0.08em", fontWeight: 600 }}>
                Important cautions
              </p>
              <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "6px" }}>
                {result.bicarb_protocol.cautions.map((c, i) => (
                  <li key={i} style={{ fontSize: "12px", color: "var(--text-muted)", display: "flex", gap: "8px" }}>
                    <span>·</span>{c}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* Nomio */}
      {result.nomio_protocol && (
        <div style={{ marginBottom: "28px" }}>
          <SectionTitle>Nomio protocol</SectionTitle>
          <div
            style={{
              border: "1px solid var(--border)",
              borderRadius: "4px",
              padding: "16px",
              background: "var(--surface)",
            }}
          >
            <p style={{ fontSize: "13px", color: "var(--text)", marginBottom: "12px", lineHeight: 1.6 }}>
              {result.nomio_protocol.timing_text}
            </p>
            <p style={{ fontSize: "12px", color: "var(--text-muted)", marginBottom: "12px" }}>
              {result.nomio_protocol.serving_note}
            </p>
            <div
              style={{
                background: "rgba(255,68,68,0.07)",
                border: "1px solid rgba(255,68,68,0.2)",
                borderRadius: "4px",
                padding: "12px",
              }}
            >
              <p style={{ fontSize: "11px", color: "var(--danger)", marginBottom: "8px", textTransform: "uppercase", letterSpacing: "0.08em", fontWeight: 600 }}>
                Important cautions
              </p>
              <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "6px" }}>
                {result.nomio_protocol.cautions.map((c, i) => (
                  <li key={i} style={{ fontSize: "12px", color: "var(--text-muted)", display: "flex", gap: "8px" }}>
                    <span>·</span>{c}
                  </li>
                ))}
              </ul>
            </div>
          </div>
        </div>
      )}

      {/* Notes */}
      <div style={{ marginBottom: "36px" }}>
        <SectionTitle>Notes</SectionTitle>
        <ul style={{ listStyle: "none", padding: 0, margin: 0, display: "flex", flexDirection: "column", gap: "8px" }}>
          {result.notes.map((note, i) => (
            <li key={i} style={{ fontSize: "13px", color: "var(--text-muted)", display: "flex", gap: "10px", lineHeight: 1.6 }}>
              <span style={{ color: "var(--text-muted)", flexShrink: 0 }}>·</span>
              {note}
            </li>
          ))}
        </ul>
      </div>

      {/* Share section */}
      <div style={{ marginBottom: "28px" }}>
        <ShareSection result={result} planValues={planValues} />
      </div>

      {/* Save plan / email capture */}
      <div
        style={{
          marginBottom: "28px",
          padding: "20px",
          background: "var(--surface)",
          border: "1px solid var(--border)",
          borderRadius: "4px",
        }}
      >
        <SectionTitle>Save your plan</SectionTitle>
        <p style={{ fontSize: "13px", color: "var(--text-muted)", marginBottom: "14px" }}>
          Enter your email and we&apos;ll keep a copy of this plan for you.
        </p>
        <SavePlanForm result={result} planValues={planValues} name={name} />
      </div>

      {/* Start over */}
      <div
        style={{
          paddingTop: "20px",
          borderTop: "1px solid var(--border)",
        }}
      >
        <button
          onClick={onStartOver}
          style={{
            padding: "12px 24px",
            background: "transparent",
            color: "var(--text-muted)",
            fontWeight: 500,
            fontSize: "14px",
            borderRadius: "4px",
            border: "1px solid var(--border)",
            cursor: "pointer",
          }}
        >
          Start over
        </button>
      </div>
    </div>
  );
}
