export const metadata = {
  title: "Disclaimer — concept//fuel",
};

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div style={{ marginBottom: "32px" }}>
      <h2
        style={{
          fontSize: "14px",
          fontWeight: 600,
          color: "var(--text)",
          marginBottom: "10px",
          letterSpacing: "-0.01em",
        }}
      >
        {title}
      </h2>
      <div
        style={{
          fontSize: "13px",
          color: "var(--text-muted)",
          lineHeight: 1.75,
        }}
      >
        {children}
      </div>
    </div>
  );
}

export default function DisclaimerPage() {
  return (
    <div style={{ maxWidth: "680px", margin: "0 auto", padding: "60px 20px" }}>
      <p
        style={{
          fontSize: "11px",
          color: "var(--text-muted)",
          letterSpacing: "0.12em",
          textTransform: "uppercase",
          marginBottom: "16px",
        }}
      >
        Legal
      </p>
      <h1
        style={{
          fontSize: "28px",
          fontWeight: 700,
          letterSpacing: "-0.03em",
          marginBottom: "8px",
        }}
      >
        Disclaimer
      </h1>
      <p style={{ fontSize: "13px", color: "var(--text-muted)", marginBottom: "40px" }}>
        Last updated: March 2026
      </p>

      <Section title="Not medical or clinical advice">
        <p>
          concept//fuel provides general sports nutrition guidance based on
          publicly available, evidence-informed frameworks. Nothing on this
          platform constitutes medical, clinical, or dietetic advice. Always
          consult a qualified healthcare professional or registered sports
          dietitian before making significant changes to your nutrition or
          supplementation strategy, particularly if you have existing medical
          conditions or take prescription medication.
        </p>
      </Section>

      <Section title="Practise in training first">
        <p>
          All plans generated by concept//fuel are starting points. Individual
          responses to carbohydrate, fluid, sodium, caffeine, and bicarbonate
          strategies vary considerably. You must practise any fuelling strategy
          in training before applying it in a race or key event. Never trial a
          new strategy on race day for the first time.
        </p>
      </Section>

      <Section title="Caffeine">
        <p>
          Caffeine guidance provided is weight-based and conservative. Caffeine
          can cause adverse effects including heart palpitations, anxiety,
          insomnia, and gastrointestinal distress. Do not use caffeine
          supplementation if you are sensitive to stimulants, pregnant, have
          cardiovascular conditions, or are taking medication that may interact
          with caffeine. The ranges provided are informational only.
        </p>
      </Section>

      <Section title="Bicarbonate (bicarb) and sodium bicarbonate">
        <p>
          Bicarbonate supplementation (whether Maurten Bicarb System, Flycarb,
          or any other product) carries significant gastrointestinal risk
          including nausea, bloating, cramping, vomiting, and diarrhoea. This
          risk is heightened at higher doses and in individuals who have not
          trialled the protocol before. Do not use bicarb products if you have
          kidney disease, high blood pressure, or are on medications that affect
          sodium or acid-base balance. Consult a clinician before use.
          concept//fuel accepts no liability for adverse outcomes from bicarb
          use.
        </p>
      </Section>

      <Section title="Nomio (broccoli sprout / sulforaphane)">
        <p>
          Nomio is a broccoli sprout concentrate containing stabilised
          isothiocyanates (sulforaphane). Research on sulforaphane in sport is
          emerging and protocols may evolve. Nomio is a separate supplement
          from bicarbonate and should not be confused with sodium bicarbonate
          products. Some individuals may experience gastrointestinal discomfort.
          Trial before any race or key event. Consult a clinician before use
          if you have medical conditions or take regular medication.
        </p>
      </Section>

      <Section title="GI (gastrointestinal) risk">
        <p>
          High carbohydrate intake during exercise (particularly above 60 g/hr)
          carries GI risk. This risk increases with intensity, heat, and
          individual variability. Targets provided are based on population-level
          research and do not account for your individual gut tolerance. Start
          conservatively and build up through training.
        </p>
      </Section>

      <Section title="No liability">
        <p>
          Concept Athletic Ltd and the concept//fuel platform accept no
          liability for any adverse health outcomes, race-day issues,
          gastrointestinal distress, or other consequences arising from the use
          of plans generated by this tool. Use at your own risk.
        </p>
      </Section>

      <Section title="Accuracy">
        <p>
          While plans are generated using deterministic logic based on
          evidence-informed guidelines, we make no warranties about the
          accuracy, completeness, or suitability of any plan for your specific
          circumstances. Sports nutrition science evolves; recommendations may
          change.
        </p>
      </Section>
    </div>
  );
}
